default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_520_ci
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: valetbike_development
<<<<<<< HEAD
  username: <%= ENV['MYSQL_USERNAME'] || '' %>
  password: <%= ENV['MYSQL_PASSWORD'] || '' %>
=======
  #username: root
  #password: rootroot
  username: root
  password: rootroot
>>>>>>> fa699f9e590c812a48ce83734065800da48f3d7c


test:
  <<: *default
  database: valetbike_test
  username: root
  password:
<<<<<<< HEAD
=======

>>>>>>> fa699f9e590c812a48ce83734065800da48f3d7c


production:
  <<: *default
  database: valetbike_production
  username: root
<<<<<<< HEAD
  password:
=======
  password: 
>>>>>>> fa699f9e590c812a48ce83734065800da48f3d7c
